# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kube-dsl/all/kube-dsl.rbi
#
# kube-dsl-0.7.1

module KubeDSL
end
class KubeDSL::SerializeHandler
  def block; end
  def field; end
  def handle(res, inflector); end
  def initialize(namespace, version, kind, field, &block); end
  def kind; end
  def matches?(ref, field); end
  def namespace; end
  def version; end
end
