module KubeDSL::DSL
  autoload :Admissionregistration, 'kube-dsl/dsl/admissionregistration'
  autoload :Apps, 'kube-dsl/dsl/apps'
  autoload :Auditregistration, 'kube-dsl/dsl/auditregistration'
  autoload :Authentication, 'kube-dsl/dsl/authentication'
  autoload :Authorization, 'kube-dsl/dsl/authorization'
  autoload :Autoscaling, 'kube-dsl/dsl/autoscaling'
  autoload :Batch, 'kube-dsl/dsl/batch'
  autoload :Certificates, 'kube-dsl/dsl/certificates'
  autoload :Coordination, 'kube-dsl/dsl/coordination'
  autoload :V1, 'kube-dsl/dsl/v1'
  autoload :Discovery, 'kube-dsl/dsl/discovery'
  autoload :Events, 'kube-dsl/dsl/events'
  autoload :Extensions, 'kube-dsl/dsl/extensions'
  autoload :Flowcontrol, 'kube-dsl/dsl/flowcontrol'
  autoload :Networking, 'kube-dsl/dsl/networking'
  autoload :Node, 'kube-dsl/dsl/node'
  autoload :Policy, 'kube-dsl/dsl/policy'
  autoload :Rbac, 'kube-dsl/dsl/rbac'
  autoload :Scheduling, 'kube-dsl/dsl/scheduling'
  autoload :Settings, 'kube-dsl/dsl/settings'
  autoload :Storage, 'kube-dsl/dsl/storage'
  autoload :Apiextensions, 'kube-dsl/dsl/apiextensions'
  autoload :Meta, 'kube-dsl/dsl/meta'
  autoload :Pkg, 'kube-dsl/dsl/pkg'
  autoload :Apiregistration, 'kube-dsl/dsl/apiregistration'
end
