module KubeDSL::DSL::Apiextensions::V1beta1
  autoload :CustomResourceColumnDefinition, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_column_definition'
  autoload :CustomResourceConversion, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_conversion'
  autoload :CustomResourceDefinition, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition'
  autoload :CustomResourceDefinitionCondition, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_condition'
  autoload :CustomResourceDefinitionList, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_list'
  autoload :CustomResourceDefinitionNames, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_names'
  autoload :CustomResourceDefinitionSpec, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_spec'
  autoload :CustomResourceDefinitionStatus, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_status'
  autoload :CustomResourceDefinitionVersion, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_definition_version'
  autoload :CustomResourceSubresourceScale, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_subresource_scale'
  autoload :CustomResourceSubresources, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_subresources'
  autoload :CustomResourceValidation, 'kube-dsl/dsl/apiextensions/v1beta1/custom_resource_validation'
  autoload :ExternalDocumentation, 'kube-dsl/dsl/apiextensions/v1beta1/external_documentation'
  autoload :JSONSchemaProps, 'kube-dsl/dsl/apiextensions/v1beta1/json_schema_props'
  autoload :ServiceReference, 'kube-dsl/dsl/apiextensions/v1beta1/service_reference'
  autoload :WebhookClientConfig, 'kube-dsl/dsl/apiextensions/v1beta1/webhook_client_config'
end
