module KubeDSL::DSL::Autoscaling::V2
  autoload :ContainerResourceMetricSource, 'kube-dsl/dsl/autoscaling/v2/container_resource_metric_source'
  autoload :ContainerResourceMetricStatus, 'kube-dsl/dsl/autoscaling/v2/container_resource_metric_status'
  autoload :CrossVersionObjectReference, 'kube-dsl/dsl/autoscaling/v2/cross_version_object_reference'
  autoload :ExternalMetricSource, 'kube-dsl/dsl/autoscaling/v2/external_metric_source'
  autoload :ExternalMetricStatus, 'kube-dsl/dsl/autoscaling/v2/external_metric_status'
  autoload :HPAScalingPolicy, 'kube-dsl/dsl/autoscaling/v2/hpa_scaling_policy'
  autoload :HPAScalingRules, 'kube-dsl/dsl/autoscaling/v2/hpa_scaling_rules'
  autoload :HorizontalPodAutoscaler, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler'
  autoload :HorizontalPodAutoscalerBehavior, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler_behavior'
  autoload :HorizontalPodAutoscalerCondition, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler_condition'
  autoload :HorizontalPodAutoscalerList, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler_list'
  autoload :HorizontalPodAutoscalerSpec, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler_spec'
  autoload :HorizontalPodAutoscalerStatus, 'kube-dsl/dsl/autoscaling/v2/horizontal_pod_autoscaler_status'
  autoload :MetricIdentifier, 'kube-dsl/dsl/autoscaling/v2/metric_identifier'
  autoload :MetricSpec, 'kube-dsl/dsl/autoscaling/v2/metric_spec'
  autoload :MetricStatus, 'kube-dsl/dsl/autoscaling/v2/metric_status'
  autoload :MetricTarget, 'kube-dsl/dsl/autoscaling/v2/metric_target'
  autoload :MetricValueStatus, 'kube-dsl/dsl/autoscaling/v2/metric_value_status'
  autoload :ObjectMetricSource, 'kube-dsl/dsl/autoscaling/v2/object_metric_source'
  autoload :ObjectMetricStatus, 'kube-dsl/dsl/autoscaling/v2/object_metric_status'
  autoload :PodsMetricSource, 'kube-dsl/dsl/autoscaling/v2/pods_metric_source'
  autoload :PodsMetricStatus, 'kube-dsl/dsl/autoscaling/v2/pods_metric_status'
  autoload :ResourceMetricSource, 'kube-dsl/dsl/autoscaling/v2/resource_metric_source'
  autoload :ResourceMetricStatus, 'kube-dsl/dsl/autoscaling/v2/resource_metric_status'
end
