# typed: strict
module KubeDSL::DSL::Autoscaling::V2beta1
  autoload :ContainerResourceMetricSource, 'kube-dsl/dsl/autoscaling/v2beta1/container_resource_metric_source'
  autoload :ContainerResourceMetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/container_resource_metric_status'
  autoload :CrossVersionObjectReference, 'kube-dsl/dsl/autoscaling/v2beta1/cross_version_object_reference'
  autoload :ExternalMetricSource, 'kube-dsl/dsl/autoscaling/v2beta1/external_metric_source'
  autoload :ExternalMetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/external_metric_status'
  autoload :HorizontalPodAutoscaler, 'kube-dsl/dsl/autoscaling/v2beta1/horizontal_pod_autoscaler'
  autoload :HorizontalPodAutoscalerCondition, 'kube-dsl/dsl/autoscaling/v2beta1/horizontal_pod_autoscaler_condition'
  autoload :HorizontalPodAutoscalerList, 'kube-dsl/dsl/autoscaling/v2beta1/horizontal_pod_autoscaler_list'
  autoload :HorizontalPodAutoscalerSpec, 'kube-dsl/dsl/autoscaling/v2beta1/horizontal_pod_autoscaler_spec'
  autoload :HorizontalPodAutoscalerStatus, 'kube-dsl/dsl/autoscaling/v2beta1/horizontal_pod_autoscaler_status'
  autoload :MetricSpec, 'kube-dsl/dsl/autoscaling/v2beta1/metric_spec'
  autoload :MetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/metric_status'
  autoload :ObjectMetricSource, 'kube-dsl/dsl/autoscaling/v2beta1/object_metric_source'
  autoload :ObjectMetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/object_metric_status'
  autoload :PodsMetricSource, 'kube-dsl/dsl/autoscaling/v2beta1/pods_metric_source'
  autoload :PodsMetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/pods_metric_status'
  autoload :ResourceMetricSource, 'kube-dsl/dsl/autoscaling/v2beta1/resource_metric_source'
  autoload :ResourceMetricStatus, 'kube-dsl/dsl/autoscaling/v2beta1/resource_metric_status'
end
