module KubeDSL::DSL::Policy::V1beta1
  autoload :AllowedCSIDriver, 'kube-dsl/dsl/policy/v1beta1/allowed_csi_driver'
  autoload :AllowedFlexVolume, 'kube-dsl/dsl/policy/v1beta1/allowed_flex_volume'
  autoload :AllowedHostPath, 'kube-dsl/dsl/policy/v1beta1/allowed_host_path'
  autoload :FSGroupStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/fs_group_strategy_options'
  autoload :HostPortRange, 'kube-dsl/dsl/policy/v1beta1/host_port_range'
  autoload :IDRange, 'kube-dsl/dsl/policy/v1beta1/id_range'
  autoload :PodDisruptionBudget, 'kube-dsl/dsl/policy/v1beta1/pod_disruption_budget'
  autoload :PodDisruptionBudgetList, 'kube-dsl/dsl/policy/v1beta1/pod_disruption_budget_list'
  autoload :PodDisruptionBudgetSpec, 'kube-dsl/dsl/policy/v1beta1/pod_disruption_budget_spec'
  autoload :PodDisruptionBudgetStatus, 'kube-dsl/dsl/policy/v1beta1/pod_disruption_budget_status'
  autoload :PodSecurityPolicy, 'kube-dsl/dsl/policy/v1beta1/pod_security_policy'
  autoload :PodSecurityPolicyList, 'kube-dsl/dsl/policy/v1beta1/pod_security_policy_list'
  autoload :PodSecurityPolicySpec, 'kube-dsl/dsl/policy/v1beta1/pod_security_policy_spec'
  autoload :RunAsGroupStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/run_as_group_strategy_options'
  autoload :RunAsUserStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/run_as_user_strategy_options'
  autoload :RuntimeClassStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/runtime_class_strategy_options'
  autoload :SELinuxStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/se_linux_strategy_options'
  autoload :SupplementalGroupsStrategyOptions, 'kube-dsl/dsl/policy/v1beta1/supplemental_groups_strategy_options'
end
