module KubeDSL::DSL::Apps::V1beta1
  autoload :ControllerRevision, 'kube-dsl/dsl/apps/v1beta1/controller_revision'
  autoload :ControllerRevisionList, 'kube-dsl/dsl/apps/v1beta1/controller_revision_list'
  autoload :Deployment, 'kube-dsl/dsl/apps/v1beta1/deployment'
  autoload :DeploymentCondition, 'kube-dsl/dsl/apps/v1beta1/deployment_condition'
  autoload :DeploymentList, 'kube-dsl/dsl/apps/v1beta1/deployment_list'
  autoload :DeploymentRollback, 'kube-dsl/dsl/apps/v1beta1/deployment_rollback'
  autoload :DeploymentSpec, 'kube-dsl/dsl/apps/v1beta1/deployment_spec'
  autoload :DeploymentStatus, 'kube-dsl/dsl/apps/v1beta1/deployment_status'
  autoload :DeploymentStrategy, 'kube-dsl/dsl/apps/v1beta1/deployment_strategy'
  autoload :RollbackConfig, 'kube-dsl/dsl/apps/v1beta1/rollback_config'
  autoload :RollingUpdateDeployment, 'kube-dsl/dsl/apps/v1beta1/rolling_update_deployment'
  autoload :RollingUpdateStatefulSetStrategy, 'kube-dsl/dsl/apps/v1beta1/rolling_update_stateful_set_strategy'
  autoload :Scale, 'kube-dsl/dsl/apps/v1beta1/scale'
  autoload :ScaleSpec, 'kube-dsl/dsl/apps/v1beta1/scale_spec'
  autoload :ScaleStatus, 'kube-dsl/dsl/apps/v1beta1/scale_status'
  autoload :StatefulSet, 'kube-dsl/dsl/apps/v1beta1/stateful_set'
  autoload :StatefulSetCondition, 'kube-dsl/dsl/apps/v1beta1/stateful_set_condition'
  autoload :StatefulSetList, 'kube-dsl/dsl/apps/v1beta1/stateful_set_list'
  autoload :StatefulSetSpec, 'kube-dsl/dsl/apps/v1beta1/stateful_set_spec'
  autoload :StatefulSetStatus, 'kube-dsl/dsl/apps/v1beta1/stateful_set_status'
  autoload :StatefulSetUpdateStrategy, 'kube-dsl/dsl/apps/v1beta1/stateful_set_update_strategy'
end
