module KubeDSL::DSL::Apiextensions
  autoload :CustomResourceColumnDefinition, 'kube-dsl/dsl/apiextensions/custom_resource_column_definition'
  autoload :CustomResourceConversion, 'kube-dsl/dsl/apiextensions/custom_resource_conversion'
  autoload :CustomResourceDefinition, 'kube-dsl/dsl/apiextensions/custom_resource_definition'
  autoload :CustomResourceDefinitionCondition, 'kube-dsl/dsl/apiextensions/custom_resource_definition_condition'
  autoload :CustomResourceDefinitionList, 'kube-dsl/dsl/apiextensions/custom_resource_definition_list'
  autoload :CustomResourceDefinitionNames, 'kube-dsl/dsl/apiextensions/custom_resource_definition_names'
  autoload :CustomResourceDefinitionSpec, 'kube-dsl/dsl/apiextensions/custom_resource_definition_spec'
  autoload :CustomResourceDefinitionStatus, 'kube-dsl/dsl/apiextensions/custom_resource_definition_status'
  autoload :CustomResourceDefinitionVersion, 'kube-dsl/dsl/apiextensions/custom_resource_definition_version'
  autoload :CustomResourceSubresourceScale, 'kube-dsl/dsl/apiextensions/custom_resource_subresource_scale'
  autoload :CustomResourceSubresourceStatus, 'kube-dsl/dsl/apiextensions/custom_resource_subresource_status'
  autoload :CustomResourceSubresources, 'kube-dsl/dsl/apiextensions/custom_resource_subresources'
  autoload :CustomResourceValidation, 'kube-dsl/dsl/apiextensions/custom_resource_validation'
  autoload :ExternalDocumentation, 'kube-dsl/dsl/apiextensions/external_documentation'
  autoload :JSON, 'kube-dsl/dsl/apiextensions/json'
  autoload :JSONSchemaProps, 'kube-dsl/dsl/apiextensions/json_schema_props'
  autoload :JSONSchemaPropsOrArray, 'kube-dsl/dsl/apiextensions/json_schema_props_or_array'
  autoload :JSONSchemaPropsOrBool, 'kube-dsl/dsl/apiextensions/json_schema_props_or_bool'
  autoload :JSONSchemaPropsOrStringArray, 'kube-dsl/dsl/apiextensions/json_schema_props_or_string_array'
  autoload :ServiceReference, 'kube-dsl/dsl/apiextensions/service_reference'
  autoload :WebhookClientConfig, 'kube-dsl/dsl/apiextensions/webhook_client_config'
  autoload :WebhookConversion, 'kube-dsl/dsl/apiextensions/webhook_conversion'
end
