module KubeDSL::DSL::Autoscaling
  autoload :CrossVersionObjectReference, 'kube-dsl/dsl/autoscaling/cross_version_object_reference'
  autoload :HorizontalPodAutoscaler, 'kube-dsl/dsl/autoscaling/horizontal_pod_autoscaler'
  autoload :HorizontalPodAutoscalerList, 'kube-dsl/dsl/autoscaling/horizontal_pod_autoscaler_list'
  autoload :HorizontalPodAutoscalerSpec, 'kube-dsl/dsl/autoscaling/horizontal_pod_autoscaler_spec'
  autoload :HorizontalPodAutoscalerStatus, 'kube-dsl/dsl/autoscaling/horizontal_pod_autoscaler_status'
  autoload :Scale, 'kube-dsl/dsl/autoscaling/scale'
  autoload :ScaleSpec, 'kube-dsl/dsl/autoscaling/scale_spec'
  autoload :ScaleStatus, 'kube-dsl/dsl/autoscaling/scale_status'
  autoload :ExternalMetricSource, 'kube-dsl/dsl/autoscaling/external_metric_source'
  autoload :ExternalMetricStatus, 'kube-dsl/dsl/autoscaling/external_metric_status'
  autoload :HorizontalPodAutoscalerCondition, 'kube-dsl/dsl/autoscaling/horizontal_pod_autoscaler_condition'
  autoload :MetricSpec, 'kube-dsl/dsl/autoscaling/metric_spec'
  autoload :MetricStatus, 'kube-dsl/dsl/autoscaling/metric_status'
  autoload :ObjectMetricSource, 'kube-dsl/dsl/autoscaling/object_metric_source'
  autoload :ObjectMetricStatus, 'kube-dsl/dsl/autoscaling/object_metric_status'
  autoload :PodsMetricSource, 'kube-dsl/dsl/autoscaling/pods_metric_source'
  autoload :PodsMetricStatus, 'kube-dsl/dsl/autoscaling/pods_metric_status'
  autoload :ResourceMetricSource, 'kube-dsl/dsl/autoscaling/resource_metric_source'
  autoload :ResourceMetricStatus, 'kube-dsl/dsl/autoscaling/resource_metric_status'
  autoload :MetricIdentifier, 'kube-dsl/dsl/autoscaling/metric_identifier'
  autoload :MetricTarget, 'kube-dsl/dsl/autoscaling/metric_target'
  autoload :MetricValueStatus, 'kube-dsl/dsl/autoscaling/metric_value_status'
end
