module KubeDSL::DSL::Policy
  autoload :AllowedCSIDriver, 'kube-dsl/dsl/policy/allowed_csi_driver'
  autoload :AllowedFlexVolume, 'kube-dsl/dsl/policy/allowed_flex_volume'
  autoload :AllowedHostPath, 'kube-dsl/dsl/policy/allowed_host_path'
  autoload :Eviction, 'kube-dsl/dsl/policy/eviction'
  autoload :FSGroupStrategyOptions, 'kube-dsl/dsl/policy/fs_group_strategy_options'
  autoload :HostPortRange, 'kube-dsl/dsl/policy/host_port_range'
  autoload :IDRange, 'kube-dsl/dsl/policy/id_range'
  autoload :PodDisruptionBudget, 'kube-dsl/dsl/policy/pod_disruption_budget'
  autoload :PodDisruptionBudgetList, 'kube-dsl/dsl/policy/pod_disruption_budget_list'
  autoload :PodDisruptionBudgetSpec, 'kube-dsl/dsl/policy/pod_disruption_budget_spec'
  autoload :PodDisruptionBudgetStatus, 'kube-dsl/dsl/policy/pod_disruption_budget_status'
  autoload :PodSecurityPolicy, 'kube-dsl/dsl/policy/pod_security_policy'
  autoload :PodSecurityPolicyList, 'kube-dsl/dsl/policy/pod_security_policy_list'
  autoload :PodSecurityPolicySpec, 'kube-dsl/dsl/policy/pod_security_policy_spec'
  autoload :RunAsGroupStrategyOptions, 'kube-dsl/dsl/policy/run_as_group_strategy_options'
  autoload :RunAsUserStrategyOptions, 'kube-dsl/dsl/policy/run_as_user_strategy_options'
  autoload :RuntimeClassStrategyOptions, 'kube-dsl/dsl/policy/runtime_class_strategy_options'
  autoload :SELinuxStrategyOptions, 'kube-dsl/dsl/policy/se_linux_strategy_options'
  autoload :SupplementalGroupsStrategyOptions, 'kube-dsl/dsl/policy/supplemental_groups_strategy_options'
end
