module KubeDSL::DSL::Meta::V1
  autoload :APIGroup, 'kube-dsl/dsl/meta/v1/api_group'
  autoload :APIGroupList, 'kube-dsl/dsl/meta/v1/api_group_list'
  autoload :APIResource, 'kube-dsl/dsl/meta/v1/api_resource'
  autoload :APIResourceList, 'kube-dsl/dsl/meta/v1/api_resource_list'
  autoload :APIVersions, 'kube-dsl/dsl/meta/v1/api_versions'
  autoload :DeleteOptions, 'kube-dsl/dsl/meta/v1/delete_options'
  autoload :GroupVersionForDiscovery, 'kube-dsl/dsl/meta/v1/group_version_for_discovery'
  autoload :LabelSelector, 'kube-dsl/dsl/meta/v1/label_selector'
  autoload :LabelSelectorRequirement, 'kube-dsl/dsl/meta/v1/label_selector_requirement'
  autoload :ListMeta, 'kube-dsl/dsl/meta/v1/list_meta'
  autoload :ManagedFieldsEntry, 'kube-dsl/dsl/meta/v1/managed_fields_entry'
  autoload :ObjectMeta, 'kube-dsl/dsl/meta/v1/object_meta'
  autoload :OwnerReference, 'kube-dsl/dsl/meta/v1/owner_reference'
  autoload :Preconditions, 'kube-dsl/dsl/meta/v1/preconditions'
  autoload :ServerAddressByClientCIDR, 'kube-dsl/dsl/meta/v1/server_address_by_client_cidr'
  autoload :Status, 'kube-dsl/dsl/meta/v1/status'
  autoload :StatusCause, 'kube-dsl/dsl/meta/v1/status_cause'
  autoload :StatusDetails, 'kube-dsl/dsl/meta/v1/status_details'
  autoload :WatchEvent, 'kube-dsl/dsl/meta/v1/watch_event'
end
