module KubeDSL::DSL::Flowcontrol::V1alpha1
  autoload :FlowDistinguisherMethod, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_distinguisher_method'
  autoload :FlowSchema, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_schema'
  autoload :FlowSchemaCondition, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_schema_condition'
  autoload :FlowSchemaList, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_schema_list'
  autoload :FlowSchemaSpec, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_schema_spec'
  autoload :FlowSchemaStatus, 'kube-dsl/dsl/flowcontrol/v1alpha1/flow_schema_status'
  autoload :GroupSubject, 'kube-dsl/dsl/flowcontrol/v1alpha1/group_subject'
  autoload :LimitResponse, 'kube-dsl/dsl/flowcontrol/v1alpha1/limit_response'
  autoload :LimitedPriorityLevelConfiguration, 'kube-dsl/dsl/flowcontrol/v1alpha1/limited_priority_level_configuration'
  autoload :NonResourcePolicyRule, 'kube-dsl/dsl/flowcontrol/v1alpha1/non_resource_policy_rule'
  autoload :PolicyRulesWithSubjects, 'kube-dsl/dsl/flowcontrol/v1alpha1/policy_rules_with_subjects'
  autoload :PriorityLevelConfiguration, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration'
  autoload :PriorityLevelConfigurationCondition, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration_condition'
  autoload :PriorityLevelConfigurationList, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration_list'
  autoload :PriorityLevelConfigurationReference, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration_reference'
  autoload :PriorityLevelConfigurationSpec, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration_spec'
  autoload :PriorityLevelConfigurationStatus, 'kube-dsl/dsl/flowcontrol/v1alpha1/priority_level_configuration_status'
  autoload :QueuingConfiguration, 'kube-dsl/dsl/flowcontrol/v1alpha1/queuing_configuration'
  autoload :ResourcePolicyRule, 'kube-dsl/dsl/flowcontrol/v1alpha1/resource_policy_rule'
  autoload :ServiceAccountSubject, 'kube-dsl/dsl/flowcontrol/v1alpha1/service_account_subject'
  autoload :Subject, 'kube-dsl/dsl/flowcontrol/v1alpha1/subject'
  autoload :UserSubject, 'kube-dsl/dsl/flowcontrol/v1alpha1/user_subject'
end
